spring:

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        temp.use_jdbc_metadata_defaults: false
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  profiles:
    include: aws

logging:
  level:
    com.tutorial: debug

server:
  port: 8081
  
jwt:
  secret: flyingwhalestimburtonconceptsandstructureofdatapencilnature!@##
